---
name: Check spelling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Codespell
        uses: codespell-project/actions-codespell@v2

        with:
          skip: "*.png,*.jpg,*.jpeg,*.gif,*.svg,*.ico,*.pdf,*.mp4,*.mov,*.avi,*.mkv,*.zip,*.tar,*.gz,*.7z"